/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-10-04 02:04:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BKRV.book.bkDAO;

public final class bkInsertform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("BKRV.book.bkDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/updateform.css\">\n");
      out.write("<title>책 정보 입력 페이지</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
	String id = (String)session.getAttribute("id");
	if(!id.equals("admin")){

      out.write("\n");
      out.write("	<script>\n");
      out.write("	alert(\"권한이 없거나 세션이 만료되었습니다.\");\n");
      out.write("	history.go(-1);\n");
      out.write("	</script>\n");
 	
   } else {
      out.write("\n");
      out.write("<h2 align = \"center\">책 정보 입력</h2>\n");
      out.write("<!-- 책 상세정보 입력 -->\n");
      out.write("<form action=\"mainSession.jsp\" method=\"post\" >\n");
      out.write("<table border=\"1\" class= \"update\">\n");
      out.write("	<tr align = \"center\">\n");
      out.write("	\n");
      out.write("		<td>일련번호</td>\n");
      out.write("		<td><input type=\"text\" name=\"bk_number\" placeholder=\"8자리 일련번호\" required />\n");
      out.write("			&nbsp; &nbsp;\n");
      out.write("			<button type=\"submit\" class = \"button\">중복확인</button></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>제목</td>\n");
      out.write("		<td><input type=\"text\" name=\"bk_title\"/></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>저자</td>\n");
      out.write("		<td><input type=\"text\" name=\"bk_writer\"/></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>출판사</td>\n");
      out.write("		<td><input type=\"text\" name=\"bk_publisher\"/></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>출간일</td>\n");
      out.write("		<td><input type=\"date\" name=\"bk_pubdate\"></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>이미지</td>\n");
      out.write("		<td>&nbsp;&nbsp;&nbsp;<input type=\"file\" value=\"파일 선택\" name=\"bk_image\"/></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<td>지역</td>\n");
      out.write("		<td>\n");
      out.write("		<input type=\"radio\" name=\"bk_local\" value=\"0\" checked />국내도서\n");
      out.write("		&nbsp;&nbsp;\n");
      out.write("		<input type=\"radio\" name=\"bk_local\" value=\"1\"/>해외도서\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align=\"center\">\n");
      out.write("		<td>장르</td>\n");
      out.write("		<td>\n");
      out.write("			<select name=\"bk_genre\">\n");
      out.write("				<option value=\"0\">--문학--</option>\n");
      out.write("				<option value=\"1\">--역사--</option>\n");
      out.write("				<option value=\"2\">--소설--</option>\n");
      out.write("				<option value=\"3\">--만화--</option>\n");
      out.write("				<option value=\"4\">--기타--</option>\n");
      out.write("			</select>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align=\"center\">\n");
      out.write("		<td>ebook 유무</td>\n");
      out.write("		<td>\n");
      out.write("			<input type=\"radio\" name=\"bk_ebook\" value=\"0\" checked /> O\n");
      out.write("			<input type=\"radio\" name=\"bk_ebook\" value=\"1\"/> X\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("	<!-- 작성일 sysdate 처리 -->\n");
      out.write("	<tr align=\"center\">\n");
      out.write("		<td>상세 내용</td>\n");
      out.write("		<td>\n");
      out.write("			<textarea rows=\"10\" cols=\"74\" name=\"bk_detail\" style =\"resize:none\"></textarea></td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align=\"center\">\n");
      out.write("		<td colspan=\"2\"> 				\n");
      out.write("			<button type=\"button\" class= \"button\" onclick=\"javascript:alert('일련번호 중복확인을 해주십시오.')\">저장</button>&nbsp;&nbsp;\n");
      out.write("			<button type=\"button\" class= \"button\" onclick=\"location.href='mainSession.jsp'\">취소</button>\n");
      out.write("			<input type=\"hidden\" name=\"center\" value=\"bkInsertform2.jsp\">\n");
      out.write("	</tr>\n");
      out.write("		\n");
      out.write("</table>\n");
      out.write("</form>\n");
} 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
