/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-10-04 02:03:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import BKRV.book.bkDAO;
import BKRV.book.bkBean;
import BKRV.review.rvDAO;
import BKRV.review.rvBean;
import java.util.Vector;

public final class bkListPro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("BKRV.book.bkDAO");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("BKRV.book.bkBean");
    _jspx_imports_classes.add("BKRV.review.rvBean");
    _jspx_imports_classes.add("BKRV.review.rvDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
request.setCharacterEncoding("UTF-8");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/updateform.css\">\n");
      out.write("<title>책 리스트 조회 화면</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- bean이 없는 상태에서 가져올 때는 아래와 같이 이용 -->\n");

	String search_word_or = request.getParameter("search_word");
	String search_word = search_word_or.replace(" ","");
	if(search_word==""){ 
      out.write("\n");
      out.write("	<script>\n");
      out.write("		location.href=\"mainSession.jsp?center=noResultPro.jsp\";\n");
      out.write("	</script>\n");
	} else{
	bkDAO bdao = new bkDAO();
	Vector<bkBean> bkVec = bdao.selectBookList(search_word);
	if(bkVec.size()==0){ 
      out.write("\n");
      out.write("	<script>\n");
      out.write("		location.href=\"mainSession.jsp?center=noResultPro.jsp\";\n");
      out.write("	</script>	\n");
	} else{
	String column = "BK_title_upper";
	String value = search_word;
	int pageSize = 5;
	String pageNum = request.getParameter("pageNum");
	
	if(pageNum == null){
		pageNum = "1";
	}
	
	int count = 0;	//전체 글 개수
	int number = 0;	//페이지 넘버링 변수
	
	int currentPage = Integer.parseInt(pageNum);	//현재 페이지 저장
			
	count = bdao.getAllcount(column, value);		//전체 게시글 숫자 저장
	
	//현재 페이지에 보여줄 시작번호 설정과 끝 페이지 설정
	//데이터베이스에서 불러올 시작번호 - 1
	int startRow = (currentPage - 1) * pageSize + 1;	//1page (1 - 1) * 10 + 1 = 1
	int endRow = currentPage * pageSize;				//1page 1 * 10 = 10
	
	bkVec = bdao.allselectBoard(startRow, endRow, column, value);
	
	number = count - (currentPage - 1) * pageSize;
	for(int i=0; i < bkVec.size(); i++){
		
		bkBean bBean = bkVec.get(i);
		int bk_number = bBean.getBk_number();
		
		rvDAO rdao = new rvDAO();
		double bk_score=rdao.getScore(bk_number);
	
		String bk_title= bBean.getBk_title();

      out.write("\n");
      out.write("\n");
      out.write("<!-- 책 일부 정보 표시 -->\n");
      out.write("<table border=\"1\" class= \"update\">\n");
      out.write("	<tr align = \"center\" height=\"80\" width=\"1150\">\n");
      out.write("		<td rowspan=\"4\" width=\"250\"><div style=\"height:100%; width:100%;\"><img src=\"/image/");
      out.print(bBean.getBk_image());
      out.write("\" height=\"100%\" width=\"100%\"></div></td>\n");
      out.write("		<td height=\"20\" width=\"200\">책 일련번호</td>\n");
      out.write("		<td colspan=\"3\" height=\"20\" width=\"400\">");
      out.print(bBean.getBk_number());
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\" >\n");
      out.write("		<!-- <td> rowspan=4 -->\n");
      out.write("		<td height=\"20\" width=\"200\">책 제목</td>\n");
      out.write("		<td height=\"20\" width=\"400\"><a style=\"color:pink\" href=\"#\" onclick=\"location.href='mainSession.jsp?center=bkSelectPro.jsp&bk_number=");
      out.print(bBean.getBk_number());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(bk_title );
      out.write("</a></td>\n");
      out.write("		<td height=\"20\" width=\"200\">책 저자</td>\n");
      out.write("		<td height=\"20\" width=\"400\">");
      out.print(bBean.getBk_writer());
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<!-- <td> rowspan=4-->\n");
      out.write("		<td height=\"20\" width=\"200\">출판사</td>\n");
      out.write("		<td height=\"20\" width=\"400\">");
      out.print(bBean.getBk_publisher());
      out.write("</td>\n");
      out.write("		<td height=\"20\" width=\"200\">출간일</td>\n");
      out.write("		<td height=\"20\" width=\"400\">");
      out.print(bBean.getBk_pubdate());
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr align = \"center\">\n");
      out.write("		<!-- <td> rowspan=4 -->\n");
      out.write("		<td height=\"20\" width=\"200\">평점</td>\n");
      out.write("		<td colspan=\"3\" height=\"20\" width=\"400\">\n");
      out.write("		");
if(bk_score==0){
      out.write("\n");
      out.write("			등록된 평점이 없습니다.\n");
      out.write("		");

		} else { 
      out.write("\n");
      out.write("			");
      out.print(bk_score);
      out.write("점\n");
      out.write("		");
}
      out.write("</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("	");
}
      out.write("\n");
      out.write("	<!-- 스타트 페이지 -->\n");
      out.write("	");

	
	
	if(count > 0){
		//
		int pagecount = count / pageSize + (count % pageSize == 0 ? 0 : 1);
		int startPage = 1;
		
		if(currentPage % 10 != 0){
			startPage = (currentPage / 10) * 10 + 1;	
		}else{
			startPage = (currentPage / 10 ) * 10 - 1;
		}
		
		int pageBlock = 10;
		
		int endPage = startPage + pageBlock - 1;
		
      out.write("\n");
      out.write("		\n");
      out.write("	<div align=\"center\">\n");
      out.write("		");

		//[이전] 링크 제작
		if(endPage > pagecount){
			endPage = pagecount;	
		}
		
		if(startPage > 10){
	
      out.write("\n");
      out.write("			<a align=\"center\" href=\"mainSession.jsp?center=bkListPro.jsp?search_word=");
      out.print(search_word );
      out.write("&pageNum=");
      out.print(startPage - 10 );
      out.write("\">[previous]</a>\n");
      out.write("	");

		}
			for(int i = startPage; i <= endPage; i++){
	
      out.write("\n");
      out.write("			<a align=\"center\" href=\"mainSession.jsp?center=bkListPro.jsp?search_word=");
      out.print(search_word );
      out.write("&pageNum=");
      out.print(i );
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(i );
      out.write("]</a>\n");
      out.write("	");

			}
			
		//[이후] 링크 제작
		if(endPage < pagecount){
			endPage = pagecount;		
	
      out.write("\n");
      out.write("			<a align=\"center\" href=\"mainSession.jsp?center=bkListPro.jsp?search_word=");
      out.print(search_word );
      out.write("&pageNum=");
      out.print(startPage + 10 );
      out.write("\">[next]</a>\n");
      out.write("	");

		}
	}
	
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");

} 
}
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
