/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-09-27 01:46:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class center_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>공지사항프리뷰</title>\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/center.css\">\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("			*{ padding: 0; margin: 0; }\r\n");
      out.write("			li{ list-style: none; }\r\n");
      out.write("			a{ text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("			body{ background-color: lightgrey; }\r\n");
      out.write("			.notice{ width: 500px; height: 40px; background-color: #333333; position: relative; overflow: hidden;  }\r\n");
      out.write("			.notice h3{ float: left; width: 100px; height: 40px; color: #FFFFFF; font-size: 18px; text-align: center; line-height: 37px; }\r\n");
      out.write("			.notice ul{ width: 300px; height: 40px; position: absolute; top:0; left: 100px; }\r\n");
      out.write("			.notice li{ width: 300px; height: 40px; position: relative; }\r\n");
      out.write("\r\n");
      out.write("			/* 글자 줄임 - 영역생성 - a는 인라인이라 영역생성X => block으로 변경 */\r\n");
      out.write("			.notice li a{ display: inline-block; width: 200px; height: 40px; color: #FFFFFF; font-size: 12px; line-height: 40px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\r\n");
      out.write("			.notice li .date{ display: inline-block; position: absolute; right: 0; color: #FFFFFF; font-size: 12px; line-height: 40px; }\r\n");
      out.write("			.notice .more{ color: #FFFFFF; font-size: 12px; line-height: 40px; position: absolute; right: 20px; }\r\n");
      out.write("		</style>\r\n");
      out.write("		<script src=\"js/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			//보드프리뷰\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				//3초마다 ul의 위치값이 -40px\r\n");
      out.write("				setInterval(function(){\r\n");
      out.write("					//li한개의 높이를 담는 변수\r\n");
      out.write("					var h = $('.notice li').height();\r\n");
      out.write("					\r\n");
      out.write("					$('.notice ul').animate({\r\n");
      out.write("						top: '-=' + h\r\n");
      out.write("					},'fast',function(){ //애니메이트메서드 발생 후 주고 싶은 명령을 담음\r\n");
      out.write("						$(this).css('top',0);\r\n");
      out.write("						$('.notice li').first().appendTo('.notice ul');\r\n");
      out.write("					});\r\n");
      out.write("				},3000);\r\n");
      out.write("			});\r\n");
      out.write("			var slideIndex = 0; //slide index\r\n");
      out.write("\r\n");
      out.write("			// HTML 로드가 끝난 후 동작\r\n");
      out.write("			window.onload=function(){\r\n");
      out.write("			  showSlides(slideIndex);\r\n");
      out.write("\r\n");
      out.write("			  // Auto Move Slide\r\n");
      out.write("			  var sec = 3000;\r\n");
      out.write("			  setInterval(function(){\r\n");
      out.write("			    slideIndex++;\r\n");
      out.write("			    showSlides(slideIndex);\r\n");
      out.write("\r\n");
      out.write("			  }, sec);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			// Next/previous controls\r\n");
      out.write("			function moveSlides(n) {\r\n");
      out.write("			  slideIndex = slideIndex + n\r\n");
      out.write("			  showSlides(slideIndex);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// Thumbnail image controls\r\n");
      out.write("			function currentSlide(n) {\r\n");
      out.write("			  slideIndex = n;\r\n");
      out.write("			  showSlides(slideIndex);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function showSlides(n) {\r\n");
      out.write("\r\n");
      out.write("			  var slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("			  var dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("			  var size = slides.length;\r\n");
      out.write("\r\n");
      out.write("			  if ((n+1) > size) {\r\n");
      out.write("			    slideIndex = 0; n = 0;\r\n");
      out.write("			  }else if (n < 0) {\r\n");
      out.write("			    slideIndex = (size-1);\r\n");
      out.write("			    n = (size-1);\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  for (i = 0; i < slides.length; i++) {\r\n");
      out.write("			      slides[i].style.display = \"none\";\r\n");
      out.write("			  }\r\n");
      out.write("			  for (i = 0; i < dots.length; i++) {\r\n");
      out.write("			      dots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  slides[n].style.display = \"block\";\r\n");
      out.write("			  dots[n].className += \" active\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"notice\">\r\n");
      out.write("			<h3>공지사항</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">12월 토요영화상영이 있는 날입니다. 어린이들과 함께 방문해 주세요</a>\r\n");
      out.write("					<span class=\"date\">2018-08-29</span>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">2016년 어린이 허준교실(접수06/29~06/31)</a>\r\n");
      out.write("					<span class=\"date\">2018-06-17</span>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">제8기 문화시민봉사단(대학생) 모집</a>\r\n");
      out.write("					<span class=\"date\">2018-04-09</span>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">\"Merry 한방 떡케이크 만들기\"</a>\r\n");
      out.write("					<span class=\"date\">2018-03-20</span>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<a href=\"#\" class=\"more\">더보기+</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		  <div class=\"slideshow-container\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Full-width images with number and caption text -->\r\n");
      out.write("      <div class=\"mySlides fade\">\r\n");
      out.write("        <div class=\"numbertext\">1 / 5</div>\r\n");
      out.write("        <img src=\"http://image.kyobobook.co.kr/newimages/adcenter/IMAC/creatives/2022/09/23/61174/kyobo_newbook.jpg\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"text\">ACNE STUDIO</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mySlides fade\">\r\n");
      out.write("        <div class=\"numbertext\">2 / 5</div>\r\n");
      out.write("        <img src=\"http://image.kyobobook.co.kr/newimages/adcenter/IMAC/creatives/2022/09/23/69547/eNEWBOOK.jpg\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"text\">ACNE STUDIO</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mySlides fade\">\r\n");
      out.write("        <div class=\"numbertext\">3 / 5</div>\r\n");
      out.write("        <img src=\"http://image.kyobobook.co.kr/newimages/adcenter/IMAC/creatives/2022/09/26/66054/newbook.jpg\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"text\">ACNE STUDIO</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mySlides fade\">\r\n");
      out.write("        <div class=\"numbertext\">4 / 5</div>\r\n");
      out.write("        <img src=\"http://image.kyobobook.co.kr/dwas/images/prom/eBook/2022/0913_sam/bn/bnU_we01.jpg\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"text\">ACNE STUDIO</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mySlides fade\">\r\n");
      out.write("        <div class=\"numbertext\">5 / 5</div>\r\n");
      out.write("        <img src=\"http://image.kyobobook.co.kr/dwas/images/prom/eBook/2022/0913_sam/bn/bnU_we01.jpg\" style=\"width:100%\">\r\n");
      out.write("        <div class=\"text\">ACNE STUDIO</div>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      <!-- Next and previous buttons -->\r\n");
      out.write("      <a class=\"prev\" onclick=\"moveSlides(-1)\">&#10094;</a>\r\n");
      out.write("      <a class=\"next\" onclick=\"moveSlides(1)\">&#10095;</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    </br>\r\n");
      out.write("\r\n");
      out.write("    <!-- The dots/circles -->\r\n");
      out.write("    <div style=\"text-align:center\">\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(0)\"></span>\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(1)\"></span>\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(2)\"></span>\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(3)\"></span>\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(4)\"></span>\r\n");
      out.write("      <span class=\"dot\" onclick=\"currentSlide(5)\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
